### ISSUE TITLE
Level 3 boss is "Unbeatable"

### ISSUE THREAD

**Issue by ApprovalG** [AIESydneyStudents/CHEDESDA#6]
**Description:** The boss on level three is unbeatable and the level cannot be finished.
**Priority:** High
**Platforms:** Windows
**Build & Environment:** Build 0.9
**Reproduction:** reach level three boss, when the player tries to get past the boss they are unable to complete the game due to an invisible wall.

**Comment by GrantTheNa** [comment]
Replaced Prefabs as they were broken and are now fixed
